---
title: "Math Tracking Affect"
output: word_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## Load libraries and dataset

```{r, include=FALSE}
library(tidyverse)
library(gtsummary)
library(modelsummary)
library(jtools)
library(mice)
library(MASS)
library(dplyr)
library(haven)
library(stringr)
library(tidyr)
library(flextable)
library(forcats)
library(mice)

# Load data
hsls_raw <- read_dta("data/hsls_17_student_pets_sr_v1_0.dta")
# lowercase all variable names
names(hsls_raw) <- tolower(names(hsls_raw))

```

## Subset Data for Analysis

```{r}

hsls <- hsls_raw %>%
  # drop non-respondents
  filter(x1sqstat != 8,
         x2sqstat != 8,
         # drop no-math 9th grade
         x3thimath9 != 0,
         )

# keep relevant variables
hsls <- hsls %>%
  dplyr::select(
         starts_with("x1"),
         starts_with("x2"),
         starts_with("x3"),
         starts_with("s1"),
         starts_with("s2"),
         starts_with("w2w1st"),
         starts_with("m1"),
         stu_id
         )

# replace missing codes

# replace missing values
hsls[hsls == -9] <- NA
hsls[hsls == -8] <- NA
hsls[hsls == -7] <- NA
hsls[hsls == -6] <- NA
hsls[hsls == -5] <- NA

hsls <- labelled::drop_unused_value_labels(hsls)

```

# Data Manipulation

## Math Variables
```{r}
################################################################################
# Outcomes - Math
################################################################################

df <- hsls %>%
  #filter(
  #  !is.na(x1mthid),
  #  !is.na(x2mthid),
  #  !is.na(x2mtheff),
  #  !is.na(x1mtheff),
  #  !is.na(x1mthuti),
  #  !is.na(x2mthuti),
  #  !is.na(x1mthint),
  #  !is.na(x2mthint_r)) %>%
  mutate(
    scale_math_id1  = x1mthid,
    scale_math_id2  = x2mthid,
    scale_math_eff1 = x1mtheff,
    scale_math_eff2 = x2mtheff,
    scale_math_uti1 = x1mthuti,
    scale_math_uti2 = x2mthuti,
    scale_math_int1 = x1mthint,
    scale_math_int2 = x2mthint_r
  )

################################################################################
# Treatment - Math
################################################################################

df <- df %>%
  mutate(
    adv_math1 = case_when(
      x3thimath9 <= 4 ~ 0, # algebra 1 and below
      x3thimath9 > 4  ~ 1, # algebra one or more advanced
      TRUE ~ NA_real_
    ),
    adv_math2 = case_when(
      s2himath12 <= 5 ~ 0, #geometry and below
      #  analytic geo, trig, precalc, calc, stats, ib/ap
      s2himath12 %in% c(6,7,8,9,10,11,12,16) ~ 1, 
      s2himath12 %in% c(13,14,15,18,19) ~ 0, #integ math, business, other
      TRUE ~ NA_real_
    ),
    math_level1 = case_when(
      x3thimath9 <= 3 ~ 1, # below alg 1
      x3thimath9 == 4  ~ 2, # alg 1
      x3thimath9 == 5 ~ 3, # geometry (adv)
      x3thimath9 >= 6 ~ 4, ## above geometry double advanced
      TRUE ~ NA_real_
    ),
    math_level1 = ordered(math_level1),
    math_level2 = case_when(
       # ageo, alg 1, pre-alg, other, business, integrated math 1/2
      s2himath12 %in% c(1,2,5,13,14,18,19) ~ 1,
      # alg 2, integrated math III
      s2himath12 %in% c(3,15) ~ 2, 
       # trig/precalc, alg3, analytic geometry
      s2himath12 %in% c(4,6,7,8) ~ 3,
      # stats, calc, AP/IB
      s2himath12 %in% c(9,10,11,12,16) ~ 4,
      TRUE ~ NA_real_
    ),
    math_level2 = ordered(math_level2)
  )


################################################################################
# Prior Achievement
################################################################################

df <- df %>%
  mutate(
    math_score = x1txmtscor,
    math_score = if_else(x1txmquint < 0, NA_real_, math_score)
  )


################################################################################
# Affective Characteristics
################################################################################

vars_to_numeric <- c("s1mtchmfdiff","s1mtchtreat","s1mtchintrst","s1mtcheasy",
                     "s2mtchtreat","s2mtchintrst","s2mtcheasy")

df <- df %>%
  #mutate(across(all_of(vars_to_numeric), as.numeric)) %>%
  mutate(
    math_treat1 = as.numeric(s1mtchtreat),
    math_treat2 = as.numeric(s2mtchtreat),
    
    # reverse code so that more agreement with positive is higher
    math_easy1 =  5 - as.numeric(s1mtcheasy),
    math_easy2 =  5 - as.numeric(s2mtcheasy),
    math_interest1 =  5 - as.numeric(s1mtchintrst),
    math_interest2 =  5 - as.numeric(s2mtchintrst)
  ) 

# Create Math Teacher Scale

df <- df %>%
  mutate(
    scale_math_teach1 = 
      rowMeans(
        across(c(math_treat1, math_easy1, math_interest1))),
    scale_math_teach2 = 
      rowMeans(
        across(c(math_treat2, math_easy2, math_interest2))),
    teach_treat_std1 = as.numeric(scale(scale_math_teach1)),
    teach_treat_std2 = as.numeric(scale(scale_math_teach2))
    )
```

## Demographic & School Characteristics
```{r}
df <- df %>%
  mutate(
    female = case_when(
      x1sex == 2 ~ 1,
      x1sex == 1 ~ 0,
      TRUE ~ NA_real_
    ),
    race_ethnicity = factor(case_when(
      x1race %in% c(1,7) ~ "Another Race",
      x1race == 2 ~ "Asian",
      x1race == 3 ~ "Black",
      x1race %in% c(4,5) ~ "Latinx",
      x1race == 6 ~ "Multiple",
      x1race == 8 ~ "White",
      TRUE ~ NA_character_
    )),
    ses_quintile1 = x1sesq5,
    ses_quintile2 = x2sesq5,
    ses1 = x1ses,
    ses2 = x2ses,
    early_algebra = ifelse(s1m8 >=4 & s1m8 !=9, 1, 0),
    
    firstlang = case_when(
      x1duallang == 1 ~ "English only",
      x1duallang == 2 ~ "non-English only",
      x1duallang == 3 ~ "English and non-English equally",
      TRUE ~ NA_character_
    ),
    first_lang = factor(firstlang)
  )

df <- df %>%
  mutate(
    urban = if_else(x1locale == 1, 1, 0),
    public = case_when(
      x1control == 1 ~ 1,
      x1control == 2 ~ 0,
      TRUE ~ NA_real_
    )
  )
```

# Save Modified Data

```{r}
################################################################################
# Save Subset (WIDE)
################################################################################


write_dta(df, "data/hsls_subset_wide.dta")
```

# Subset, reshape, save
```{r}

df <- df %>%
  dplyr::select(
    scale_math_id1, scale_math_id2,
    adv_math1, adv_math2,
    math_level1, math_level2,
    scale_math_eff1, scale_math_eff2,
    scale_math_uti1, scale_math_uti2,
    scale_math_int1, scale_math_int2,
    teach_treat_std1, teach_treat_std2,
    math_treat1, math_easy1, math_interest1, 
    math_treat2, math_easy2, math_interest2,
    ses_quintile1, ses_quintile2,
    ses1, ses2,
    starts_with("math_teach"),
    early_algebra, math_score, 
    first_lang, race_ethnicity, female, 
    urban, public,
    stu_id, starts_with("w2w1s")
  )


df_long <- df %>%
  pivot_longer(
    cols = c(scale_math_id1, scale_math_id2,
             scale_math_eff1, scale_math_eff2,
             scale_math_uti1, scale_math_uti2,
             scale_math_int1, scale_math_int2,
             teach_treat_std1, teach_treat_std2,
             math_treat1, math_easy1, math_interest1, 
             math_treat2, math_easy2, math_interest2,
             adv_math1, adv_math2, math_level1, math_level2,
             ses_quintile1, ses_quintile2, ses1, ses2),
    names_to = c(".value","time"),
    names_pattern = "(.*)([12])"
  ) %>%
  mutate(
    time = if_else(time == "1", 0, 1)
  )

write_dta(df_long, "data/hsls_subset_long.dta")
```



# Imputation

## Dry run & prep
```{r}
colSums(is.na(df_long))
df_imp_prep <- df_long %>% as_factor() %>% dplyr::select(
  -math_treat1, -math_easy1, -math_interest1, 
  -math_treat2, -math_easy2, -math_interest2)
# dry run
meth <- mice::mice(df_imp_prep, maxit = 0, m = 1)
meth$method
```

## Impute!
```{r}
start_time <- Sys.time()

df_imp <- mice(df_imp_prep, m = 20, nnet.MaxNWts = 3000)
end_time <- Sys.time()
end_time - start_time
save(df_imp, file = "data/df_imp.rdata")


```


